using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Ganimed.StasisChamber;

namespace Content.Client.Ganimed.StasisChamber;

[GenerateTypedNameReferences]
public sealed partial class StasisChamberWindow : DefaultWindow
{
    public StasisChamberWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(StasisStorageConsoleState storageConsoleState)
    {
        PopulateStasisChamberRecords(storageConsoleState.StasisChamberRecords);
    }

    private void PopulateStasisChamberRecords(IEnumerable<string>? records)
    {
        StasisChamberRecord.Clear();
        StasisChamberRecord.ClearSelected();

        if (records is null)
        {
            return;
        }

        foreach (var record in records)
        {
            StasisChamberRecord.AddItem(record);
        }

        StasisChamberRecord.SortItemsByText();
    }

}