using System.Linq;
using System.Numerics;
using Content.Shared.LowDesert.Monster;
using Content.Shared.LowDesert.Monster.Components;
using Content.Client.Stylesheets;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;


namespace Content.Client.LowDesert.Monster.Ui;

[GenerateTypedNameReferences]
public sealed partial class MonsterEvolutionScreen : DefaultWindow
{
	public MonsterEvolutionScreen ()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);
	}
	
	public void UpdateState(BoundUserInterfaceState state)
	{
	}
}